.rubocop.yml, Gemfile, Gemfile.lock, Procfile.dev, app/controllers/api/v1/points_controller.rb, app/controllers/points_controller.rb, app/helpers/application_helper.rb, app/jobs/point_creating_job.rb, app/jobs/stat_creating_job.rb, app/models/stat.rb, app/services/countries_and_cities.rb, app/services/create_stats.rb, app/views/layouts/application.html.erb, app/views/points/index.html.erb, app/views/shared/_right_sidebar.html.erb, app/views/stats/index.html.erb, config/initializers/00_constants.rb, config/schedule.yml, spec/factories/imports.rb, spec/factories/points.rb, spec/jobs/import_job_spec.rb, spec/jobs/point_creating_job_spec.rb, spec/jobs/reverse_geocoding_job_spec.rb, spec/jobs/stat_creating_job_spec.rb, spec/models/stat_spec.rb, spec/models/user_spec.rb, spec/requests/api/v1/points_spec.rb, spec/services/countries_and_cities_spec.rb, spec/services/create_stats_spec.rb, spec/services/own_tracks/export_parser_spec.rb
=> Basic tests

README.md
=> Added Discord badge to README instead of link

app/services/gpx/track_parser.rb, spec/fixtures/files/gpx/gpx_track_multiple_tracks.gpx, spec/services/gpx/track_parser_spec.rb
:wave: Hi @Freika,
I was playing around with dawarich. Nice Project! 
I was playing around and tried to import my entire huge Strava/GPX Library I have locally and figured out that the GPX importer isn't working as expected. In this PR I tried to improve it so it parses all GPX files correctly.
I made the following adjustments:
- The return value of the `call` was missing the calculated Points. Thus every import created the Points but failed later on as the `ImportJob` was expecting a hash as return value. 
- A GPX File can have multiple tracks, in which you can have multiple segments. The latter was already working. The former was missing, I added it in this PR accompanied with a test.
=> Improve GPX Parser

app/controllers/map_controller.rb, app/views/map/index.html.erb
I find it more useful -and less cluttered- to start by default with today's route. This PR intends to do that, if you agree, here it is.
Cheers.
Disclaimer: this is my first ever Ruby code, hope I didn't screw up.
=> Default to today in maps page

app/views/points/index.html.erb
=> chore: update index.html.erb

docker-compose.yml
https://github.com/Freika/dawarich/issues/321
=> Adding healthcheck for containers for Docker compose configuration

CHANGELOG.md, docker-compose.yml
- `DISABLE_TELEMETRY` env var to disable telemetry. More on telemetry: https://dawarich.app/docs/tutorials/telemetry
=> Add DISABLE_TELEMETRY env var to disable telemetry

app/javascript/controllers/maps_controller.js, app/javascript/maps/polylines.js
Addresses https://github.com/Freika/dawarich/issues/381
=> Update map popup to use configured distance unit

docs/How_to_install_Dawarich_in_k8s.md
This PR adds a mention in the K8s install docs for @Cogitri's Helm chart.
[Cogitri/charts](https://github.com/Cogitri/charts/tree/master/charts/dawarich)
=> docs: Mention Helm chart by @Cogitri

app/controllers/notifications_controller.rb, app/views/notifications/index.html.erb, config/routes.rb
For a It was not posible to delete his notifications. With this change there will be a button to do so.
=> Feature: Add a "Delete Notifications" button

config/environments/development.rb
This PR adds support for changing `RAILS_LOG_LEVEL` in development.
=> Add support for changing log level in development

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .gitignore, DEVELOPMENT.md
This PR implements a devcontainer to dawarich, makes it easyer to develop with VS Code.
This now works good for me. I can use this to develop dawarich.
=> Add devcontainer to dawarich

app/services/immich/request_photos.rb
=> Add Logging for Immich

CHANGELOG.md, app/controllers/api/v1/points_controller.rb, app/javascript/controllers/maps_controller.js, app/javascript/maps/fog_of_war.js, app/javascript/maps/markers.js, app/javascript/maps/polylines.js, app/javascript/maps/popups.js, config/routes.rb
- You can now drag-n-drop a point on the map to update its position. Enable the "Points" layer on the map to see the points.
- Run seeds even in prod env so Unraid users could have default user.
- Precompile assets in production env using dummy secret key base.
- Fixed a bug where route wasn't highlighted when it was hovered or clicked.
=> Points drag-n-drop

CHANGELOG.md, app/services/check_app_version.rb, spec/services/check_app_version_spec.rb
- Fix a bug where rc version was being checked as a stable release. #711
=> Fix a bug where rc version was being checked as a stable release

docs/How_to_install_Dawarich_in_k8s.md
Update k8s deployment example
* remove unused gem-caches PV/PVCs
* update entrypoints to correspond 0.22.x
* add liveness probe
=> Update k8s deployment example

CHANGELOG.md, app/controllers/exports_controller.rb, spec/requests/exports_spec.rb
- Fixed a bug where export file was not being deleted from the server after it was deleted. #808
=> Fix deleting export file

docker/sidekiq-entrypoint.sh, docker/web-entrypoint.sh
=> Revert "fix: set dbname in psql entrypoint commands"

.github/workflows/build_and_push.yml
=> Revert "Feature/parallel docker image builds"

app/services/reverse_geocoding/places/fetch_data.rb
=> Revert "Add radius param of 10"

docker/docker-compose.yml
=> docker-compose.yml: Add PostGIS envvar to create database on initial setup.

app/assets/stylesheets/application.tailwind.css, app/views/map/index.html.erb
=> Revert "fix map container height to fit viewport"
