Freika/dawarich

- .github/workflows/main.yml
Following from [this medium article](https://www.agas.dev/github-actions-docker-build) by [Agastya Darma Laksana](https://github.com/gedeagas). This workflow allows for either the automation of or manual creation of docker images for the AMD64 and ARM64 architectures and automatically push it to a registry of choosing. 
The secrets can be set via the [project's settings](https://github.com/Freika/dawarich/settings/secrets/actions) under `Repository secrets`.
Tested with a private docker registry so can't comment on using docker hub.
> Docker ARM64/AMD64 image workflow

- docker-compose.yml
This PR addresses issue #176, but does not fully solve it. In this PR, we simply set the restart policy for Redis and the database so that it is always up. This does not solve the root cause of the issue, and I believe this issue should be researched further, but I think this is a good start.
> Set auto restart to DB & Redis in case it crashes or shuts down.

- app/controllers/api/v1/points_controller.rb
It seems like all HTTP headers are string, while other types may work, its more safe to convert the types to strings to ensure no trouble is caused by non string types. Even if it does work, at least now the types are consistent, as headers are being put as string and they are also retrieved as string.
> Convert the headers to string

- Dockerfile
- Dockerfile.dev
- config/database.yml
- dev-docker-entrypoint.sh
- dev-docker-sidekiq-entrypoint.sh
Hey!
This PR fixes #88 by modifying `dev-docker-entrypoint.sh` to use alternative ports when the env var is specified and make sure that the DB does not exist before attempting to create it. It also modifies `config/database.yml` to not override the database name when one is specified as an env var.
I also reordered the Dockerfile to optimize layer caching. This means docker builds with a cache will be near-instant as long as dependency inputs don't change.
Let me know what you think! Thank you for this project! Excited to be able to see my data in a way that OwnTracks is sorely lacking.
> Allow alternate Postgres port and DB name in Docker (fixes #88)

- app/helpers/application_helper.rb
2023 at UTC = 2022 in any of the timezones west of UTC, which resulted in the wrong timespans being calculated.
This PR fixes this by simply ignoring the user-configured TZ. When calculating timespans, the TZ is not relevant.
Fixes #194
Fixes #122
> Bugfix: when calculating the timestamp (for months and years), ignore the Timezone

- docs/How_to_install_Dawarich_using_Docker.md
I'm somewhat new to Docker, but `docker-compose` had issues with running this. `docker compose` seems to be the new standard going forward, and it indeed works when the other one fails.
> Installation: use `docker compose`, not `docker-compose`

- docker-compose.yml
After adopting changes suggested in [version 0.15.11](https://github.com/Freika/dawarich/releases/tag/0.15.11) it seems healthcheck command broke. Docker compose is trying to resolve `$HOSTNAME` variable when deploying instead of resolving it on execution time. Fixed this escaping variable character with double dollar sign, `$$`.
> Fixed $HOSTNAME variable usage in healthcheck command

- CHANGELOG.md
- app/controllers/exports_controller.rb
- Exported files will now always have an extension when downloaded. Previously, the extension was missing in case of GPX export. #377
> Fix missing file extension in gpx export files

- CHANGELOG.md
- app/controllers/points_controller.rb
- app/views/points/index.html.erb
- Deleting and sorting points on the Points page will now preserve filtering and sorting params when points are deleted or sorted. Previously, the page was being reloaded and filtering and sorting params were lost. #363
> Fix points params preserved

- docker-compose.yml
This fixes a bug where the other containers are not able to reach redis on the network because docker does not assign the expected DNS entry to the container.
> fix: Redis container missing name in compose-file

- docker-compose.yml
> docker-compose.yml: Change number of healthcheck rerties for dawarich_app and dawarich_sidekiq from 5 to 30.

- docker-compose_mounted_volumes.yml
* use local folders as db volumes to prevent data loss
* use latest postgres version
* use keydb instead of redis
* rename services and containers
* add healthchecks service dependencies
> Create new docker compose with some improvement

- config/initializers/sidekiq.rb
Certain scenarios (for instance, if one wants to perform an isolated `rake assets:precompile`) fails if Redis is not configured --and there are scenarios that do not need Redis configuration.
The edited initialization code was always triggering. It makes sense to add an `if` there and only do it in the scenarios where it is really necessary.
I am not an expert and have performed limited testing, but it seems like this allows the assets:precompile to run properly and does not break the server nor sidekiq startups.
> Avoid Redis connectivity on initialization

- CHANGELOG.md
- config/initializers/prometheus.rb
- config/initializers/sidekiq.rb
- Sidekiq is now being correctly exported to Prometheus with `PROMETHEUS_EXPORTER_ENABLED=true` env var in `dawarich_sidekiq` service.
> Fix Prometheus exporter for Sidekiq

- app/services/own_tracks/rec_parser.rb
- spec/fixtures/files/owntracks/2024-03.rec
This pull request aims to fix the issue in #464 
After investigating further from what I had posted on the issue, I realized the issue was with how the importer handled lines which didn't follow the structure of a log line of `type: location`.
For example, lines like 
```
2024-03-01T18:40:08Z	lwt               	{"_type":"lwt","tst":1717459208}
2024-03-01T18:40:09Z	waypoints         	{"_type":"waypoint","desc":"Home","lat":52.232,"lon":13.339,"rad":50,"tst":1717459768}
2024-03-01T18:40:10Z	event             	{"_type":"transition","acc":5,"desc":"Home","event":"enter","lat":52.232,"lon":13.339,"t":"l","tid":"s8","tst":1717460098,"wtst":1717459768}
```
which are valid event log lines in Owntracks would break the parser which expects a `"\t* \t"` structure.
This change should fix that. I …
> fix imports of owntracks .rec files containing log types other than events

- app/javascript/controllers/maps_controller.js
In the Map-View I often  disable the Polyline Layer, this makes it easier for me to click on a point, to delete it. But after the point is deleted, the polyline Layer is visible again. This is a fix for this.
> On Map Point delete: Hide Polyline Layer, if it was hidden before

- docker-compose.yml
- docs/How_to_install_Dawarich_in_k8s.md
It appears that gems aren't being stored in the defined volumes. I think this is a result of the change in [`d3f6d0d`](https://github.com/Freika/dawarich/commit/d3f6d0da7bc500e6af42cced82e46d7d5b783f7d#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3).
Looks like either supporting changes to write gems to a different path in app/sidekiq weren't added or the change to the path was supposed to be on the host side rather than the container side.
I'm assuming it's the latter. If so, this PR will fix the paths. The host-side paths in the compose file were already fixed in d3c80e2b18ef87af1d7927ebc88a6831bb5abd1e.
> fix gem paths in compose.yml & k8s instructions

- Procfile.dev
- Procfile.prometheus.dev
- config/puma.rb
- docs/How_to_install_Dawarich_in_k8s.md
This Pull Request binds the Rails server and Prometheus Exporter to both IPv6 and IPv4 interfaces by default, and updates the K8s deployment documentation to reflect this.
Not tested as there appears to be no scaffolding to test this functionality?
Closes https://github.com/Freika/dawarich/issues/498
> Bind to both IPv6 and IPv4 interfaces by default

- CHANGELOG.md
- app/controllers/api/v1/countries/visited_cities_controller.rb
- app/services/tasks/imports/google_records.rb
- Fix authentication to `GET /api/v1/countries/visited_cities` with header `Authorization: Bearer YOUR_API_KEY` instead of `api_key` query param. #679
> Fix authentication to `GET /api/v1/countries/visited_cities`

- docker/sidekiq-entrypoint.sh
- docker/web-entrypoint.sh
> not setting this breaks init if a custom dbname is used. This was discussed on discord last week but that context understandably got lost (https://discord.com/channels/1233340338865963079/1251100415034921052/1333517972106383411):
/var/app # env | grep DATABASE
DATABASE_NAME=dawarich
DATABASE_USERNAME=dawarich-bliT1A
DATABASE_PASSWORD=CFKsnipsx
DATABASE_HOST=app-db-rw.database.svc
>    These are my env vars, but it seems like dawarich is trying to use the username as the database name
psql: error: connection to server at "app-db-rw.database.svc" (10.43.162.18), port 5432 failed: FATAL: database "dawarich-bliT1A" does not exist
> fix: set dbname in psql entrypoint commands

- app/javascript/maps/fog_of_war.js
Closes #774
Problems:
- Fix: When draging map the 'Fog of War'gets displaced (#774).
- Fix: If the size of the browser window is changed, the size of the fog is not recalculated.
> Fix fog gets displaced when dragging map

- app/services/reverse_geocoding/places/fetch_data.rb
https://github.com/Freika/dawarich/discussions/652
> Add radius param of 10

- app/controllers/api/v1/settings_controller.rb
- app/javascript/controllers/maps_controller.js
- app/javascript/maps/fog_of_war.js
- app/views/map/_settings_modals.html.erb
I have made improvements to the fog of war map mode :
\- Neighbor points are now joined together, with a configurable maximum time threshold (default 1m30).
This fixes the issue with sparse points leaving gaps behind (more frequent when going at high speeds, or from Google Timeline imports).
|  Before  |  After  | 
|---|---|
|  ![Screenshot_246](https://github.com/user-attachments/assets/8f2086c0-2cfa-49d8-a10d-c2cb9b7ce1be)  |  ![Screenshot_244](https://github.com/user-attachments/assets/5f1d0ec1-2502-4a40-b3fe-e1ce708c7e6e)  |
Example above with gaps being filled. The only issue with this change is the lack of gradient on the sides; I have been unable to apply a proper gradient with lines.
\- Minimum line width
The line width has a minimum value of 2px, regardless of the configured …
> Fog of war improvements
